using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using NuvioTV.Core.Configuration;
using NuvioTV.Core.Networking;
using NuvioTV.Core.Storage;

namespace NuvioTV.Core.Auth
{
    /// <summary>
    /// Result of a started TV login session (JS parity: the object returned by
    /// QrLoginService.start, qrLoginService.js:406-415).
    /// </summary>
    public sealed class QrLoginStartResult
    {
        [JsonPropertyName("code")]
        public string Code { get; set; }

        [JsonPropertyName("loginUrl")]
        public string LoginUrl { get; set; }

        [JsonPropertyName("qrImageUrl")]
        public string QrImageUrl { get; set; }

        [JsonPropertyName("expiresAt")]
        public long ExpiresAtMillis { get; set; }

        [JsonPropertyName("pollIntervalSeconds")]
        public int PollIntervalSeconds { get; set; }

        [JsonPropertyName("deviceNonce")]
        public string DeviceNonce { get; set; }
    }

    /// <summary>
    /// QR device login flow: anonymous session bootstrap, start/poll/exchange of a
    /// TV login session, writing exchanged tokens into the session store.
    ///
    /// Behavioral spec (do not diverge): js/core/auth/qrLoginService.js.
    /// </summary>
    public sealed class QrLoginService
    {
        private const int DefaultPollIntervalSeconds = 3;
        private const int MinimumPollIntervalSeconds = 2;
        private const int SessionExpiryFallbackMillis = 5 * 60 * 1000;

        // JS parity: isCallerSessionRejected (qrLoginService.js:137-145).
        private static readonly string[] CallerRejectedMarkers =
        {
            "http 401",
            "invalid caller session",
            "jwt expired",
            "invalid jwt"
        };

        private readonly HttpClient _httpClient;
        private readonly SupabaseClient _supabase;
        private readonly AuthManager _auth;
        private readonly IKeyValueStore _store;
        private readonly Func<string> _deviceLabelProvider;
        private readonly Func<DateTimeOffset> _utcNow;
        private readonly Func<TimeSpan, CancellationToken, Task> _delay;

        private string _lastError;
        private string _currentDeviceNonce;

        public QrLoginService(
            HttpClient httpClient,
            AuthManager auth,
            IKeyValueStore store,
            Func<string> deviceLabelProvider = null,
            Func<DateTimeOffset> utcNow = null,
            Func<TimeSpan, CancellationToken, Task> delay = null)
        {
            _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
            _auth = auth ?? throw new ArgumentNullException(nameof(auth));
            _store = store ?? throw new ArgumentNullException(nameof(store));
            _supabase = new SupabaseClient(_httpClient, auth);
            _deviceLabelProvider = deviceLabelProvider;
            _utcNow = utcNow ?? (() => DateTimeOffset.UtcNow);
            _delay = delay ?? ((span, token) => Task.Delay(span, token));
        }

        /// <summary>Last failure message (JS parity: getLastError).</summary>
        public string LastError => _lastError;

        /// <summary>
        /// Nonce generated by the most recent StartAsync; ExchangeAsync(code) uses it
        /// when the caller does not pass one explicitly.
        /// </summary>
        public string CurrentDeviceNonce => _currentDeviceNonce;

        // -------------------------------------------------------------------
        // High-level flow (JS parity: QrLoginService.start, qrLoginService.js:357-421)
        // -------------------------------------------------------------------

        public async Task<QrLoginStartResult> StartAsync(CancellationToken ct = default)
        {
            _lastError = null;
            try
            {
                if (!HasQrAuthConfig())
                {
                    throw new InvalidOperationException("QR auth is not configured");
                }

                await EnsureQrSessionAuthenticatedAsync(false, ct).ConfigureAwait(false);

                var deviceNonce = GenerateDeviceNonce();
                var redirectCandidates = BuildRedirectCandidates();
                if (redirectCandidates.Count == 0)
                {
                    throw new InvalidOperationException("Missing redirect_base_url configuration");
                }

                JsonElement? session = null;
                Exception lastStartError = null;

                foreach (var redirectCandidate in redirectCandidates)
                {
                    try
                    {
                        session = await StartTvLoginSessionAsync(deviceNonce, redirectCandidate, true, ct).ConfigureAwait(false);
                        if (session.HasValue)
                        {
                            break;
                        }
                    }
                    catch (Exception error)
                    {
                        if (IsLegacyStartSignatureError(error.Message))
                        {
                            try
                            {
                                session = await StartTvLoginSessionAsync(deviceNonce, redirectCandidate, false, ct).ConfigureAwait(false);
                                if (session.HasValue)
                                {
                                    break;
                                }
                            }
                            catch (Exception legacyError)
                            {
                                lastStartError = legacyError;
                                continue;
                            }
                        }

                        lastStartError = error;
                        continue;
                    }
                }

                if (!session.HasValue)
                {
                    if (lastStartError != null)
                    {
                        throw new InvalidOperationException(
                            lastStartError.Message + " | tried redirect_base_url: " + string.Join(" , ", redirectCandidates));
                    }

                    throw new InvalidOperationException("Empty response from start_tv_login_session");
                }

                _currentDeviceNonce = deviceNonce;

                return BuildStartResult(session.Value, deviceNonce);
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch (Exception error)
            {
                _lastError = error.Message ?? "QR start failed";
                return null;
            }
        }

        private QrLoginStartResult BuildStartResult(JsonElement session, string deviceNonce)
        {
            var code = GetStringProperty(session, "code");
            var loginUrl = GetStringProperty(session, "qr_content") ?? GetStringProperty(session, "web_url") ?? "";
            var qrImageUrl = GetStringProperty(session, "qr_image_url")
                ?? ("https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=" + Uri.EscapeDataString(loginUrl));

            return new QrLoginStartResult
            {
                Code = code,
                LoginUrl = loginUrl.Length > 0 ? loginUrl : null,
                QrImageUrl = qrImageUrl,
                ExpiresAtMillis = ToEpochMillis(session, _utcNow),
                PollIntervalSeconds = (int)ToNumber(GetNumberProperty(session, "poll_interval_seconds"), DefaultPollIntervalSeconds),
                DeviceNonce = deviceNonce
            };
        }

        // -------------------------------------------------------------------
        // RPC steps (JS parity: startRpc / poll / exchange)
        // -------------------------------------------------------------------

        /// <summary>
        /// JS parity: startRpc (qrLoginService.js:322-350). POST rpc/start_tv_login_session
        /// with p_device_nonce + p_redirect_base_url (+ p_device_name unless omitted for
        /// legacy-signature retry). Returns data[0] or null.
        /// </summary>
        public async Task<JsonElement?> StartTvLoginSessionAsync(
            string deviceNonce,
            string redirectBaseUrl,
            bool includeDeviceName = true,
            CancellationToken ct = default)
        {
            var payload = new Dictionary<string, object>
            {
                ["p_device_nonce"] = deviceNonce,
                ["p_redirect_base_url"] = redirectBaseUrl
            };
            if (includeDeviceName)
            {
                payload["p_device_name"] = GetDeviceLabel();
            }

            var data = await WithCallerSessionRecoveryAsync(
                () => _supabase.RpcAsync("start_tv_login_session", payload, true, ct),
                ct).ConfigureAwait(false);

            return FirstArrayElement(data);
        }

        /// <summary>
        /// JS parity: QrLoginService.poll (qrLoginService.js:423-457). Returns
        /// data[0].status ("pending" | "approved" | "expired") or null on failure
        /// (LastError carries the reason).
        /// </summary>
        public async Task<string> PollTvLoginSessionAsync(string code, string deviceNonce, CancellationToken ct = default)
        {
            _lastError = null;
            try
            {
                if (!HasQrAuthConfig())
                {
                    _lastError = "QR auth is not configured";
                    return null;
                }

                var payload = new Dictionary<string, object>
                {
                    ["p_code"] = code,
                    ["p_device_nonce"] = deviceNonce
                };

                var data = await WithCallerSessionRecoveryAsync(
                    () => _supabase.RpcAsync("poll_tv_login_session", payload, true, ct),
                    ct).ConfigureAwait(false);

                var first = FirstArrayElement(data);
                if (!first.HasValue)
                {
                    return null;
                }

                return GetStringProperty(first.Value, "status");
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch (Exception error)
            {
                _lastError = error.Message ?? "QR poll failed";
                return null;
            }
        }

        /// <summary>
        /// Convenience loop over <see cref="PollTvLoginSessionAsync"/> honoring the
        /// session's poll interval and expiry (the JS screen owns setInterval timers;
        /// this ports that loop for the native screen). Returns the terminal status:
        /// "approved" / "expired" — or "expired" once expiresAtMillis passes.
        /// </summary>
        public async Task<string> PollUntilResolvedAsync(
            string code,
            string deviceNonce,
            long expiresAtMillis,
            int pollIntervalSeconds = DefaultPollIntervalSeconds,
            CancellationToken ct = default)
        {
            var interval = TimeSpan.FromSeconds(Math.Max(MinimumPollIntervalSeconds, pollIntervalSeconds));

            while (true)
            {
                var status = await PollTvLoginSessionAsync(code, deviceNonce, ct).ConfigureAwait(false);
                if (status == "approved" || status == "expired")
                {
                    return status;
                }

                if (_utcNow().ToUnixTimeMilliseconds() >= expiresAtMillis)
                {
                    return "expired";
                }

                await _delay(interval, ct).ConfigureAwait(false);
            }
        }

        /// <summary>
        /// JS parity: QrLoginService.exchange (qrLoginService.js:459-506). Exchanges the
        /// approved code via tv-logins-exchange and persists the returned tokens as a
        /// non-anonymous authenticated session. Returns false on failure (LastError set).
        /// </summary>
        public Task<bool> ExchangeAsync(string code, CancellationToken ct = default)
        {
            return ExchangeAsync(code, _currentDeviceNonce, ct);
        }

        public async Task<bool> ExchangeAsync(string code, string deviceNonce, CancellationToken ct = default)
        {
            _lastError = null;
            try
            {
                if (!HasQrAuthConfig())
                {
                    _lastError = "QR auth is not configured";
                    return false;
                }

                var result = await WithCallerSessionRecoveryAsync(
                    () => _supabase.TvLoginsExchangeAsync(code, deviceNonce, ct),
                    ct).ConfigureAwait(false);

                string accessToken;
                string refreshToken;
                if (!TryExtractSessionTokens(result, out accessToken, out refreshToken))
                {
                    _lastError = "QR exchange missing session tokens";
                    return false;
                }

                await _auth.StoreTokensAsync(accessToken, refreshToken, false, ct).ConfigureAwait(false);
                _auth.SetState(AuthState.Authenticated);
                return true;
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch (Exception error)
            {
                _lastError = error.Message ?? "QR exchange failed";
                return false;
            }
        }

        // -------------------------------------------------------------------
        // Anonymous session bootstrap
        // (JS parity: ensureQrSessionAuthenticated, qrLoginService.js:207-304)
        // -------------------------------------------------------------------

        private async Task EnsureQrSessionAuthenticatedAsync(bool forceNewAnonymous, CancellationToken ct)
        {
            if (forceNewAnonymous)
            {
                var wasAnonymous = _auth.IsAnonymousSession;
                if (!wasAnonymous && !string.IsNullOrEmpty(_auth.GetRefreshToken()))
                {
                    var refreshed = await _auth.RefreshSessionIfNeededAsync(true, ct).ConfigureAwait(false);
                    if (refreshed && !string.IsNullOrEmpty(_auth.GetAccessToken()) && !AuthManager.IsJwtExpired(_auth.GetAccessToken(), 0))
                    {
                        return;
                    }

                    if (_auth.WasLastSessionRefreshTransientFailure())
                    {
                        return;
                    }
                }

                await _auth.ClearSessionAsync().ConfigureAwait(false);
            }

            var accessToken = _auth.GetAccessToken();

            // Non-JWT access tokens are unusable for the caller session.
            if (!string.IsNullOrEmpty(accessToken) && !AuthManager.IsJwtLike(accessToken))
            {
                await _auth.ClearSessionAsync().ConfigureAwait(false);
                accessToken = null;
            }

            if (!string.IsNullOrEmpty(accessToken) && !_auth.IsAnonymousSession)
            {
                if (!AuthManager.IsJwtExpired(accessToken, 30))
                {
                    return;
                }

                var refreshed = await _auth.RefreshSessionIfNeededAsync(false, ct).ConfigureAwait(false);
                accessToken = _auth.GetAccessToken();
                if (refreshed && !string.IsNullOrEmpty(accessToken) && !AuthManager.IsJwtExpired(accessToken, 30))
                {
                    return;
                }

                if (_auth.WasLastSessionRefreshTransientFailure())
                {
                    return;
                }

                await _auth.ClearSessionAsync().ConfigureAwait(false);
                accessToken = null;
            }

            if (!string.IsNullOrEmpty(accessToken) && _auth.IsAnonymousSession)
            {
                if (!AuthManager.IsJwtExpired(accessToken, 30))
                {
                    return;
                }

                await _auth.ClearSessionAsync().ConfigureAwait(false);
            }

            string firstMessage = null;
            string signupAccess;
            string signupRefresh;
            JsonElement signupPayload;
            try
            {
                signupPayload = await _supabase.SignupAnonymousAsync(ct).ConfigureAwait(false);
            }
            catch (NuvioHttpException error)
            {
                firstMessage = error.Message;
                signupPayload = default;
            }

            // JS parity: the anonymous-token grant only runs when signup THREW; a
            // successful signup without session tokens fails outright.
            if (firstMessage == null)
            {
                if (!TryExtractSessionTokens(signupPayload, out signupAccess, out signupRefresh))
                {
                    throw new InvalidOperationException("Anonymous auth did not return session tokens");
                }

                await _auth.StoreTokensAsync(signupAccess, signupRefresh, true, ct).ConfigureAwait(false);
                return;
            }

            // JS parity: fall back to grant_type=anonymous when signup fails, combining errors.
            string secondMessage;
            try
            {
                var payload = await _supabase.AnonymousTokenAsync(ct).ConfigureAwait(false);
                if (!TryExtractSessionTokens(payload, out signupAccess, out signupRefresh))
                {
                    throw new InvalidOperationException("Anonymous auth did not return session tokens");
                }

                await _auth.StoreTokensAsync(signupAccess, signupRefresh, true, ct).ConfigureAwait(false);
            }
            catch (Exception error) when (!(error is OperationCanceledException))
            {
                secondMessage = error.Message ?? "anonymous token failed";
                throw new InvalidOperationException(
                    (firstMessage ?? "anonymous signup failed") + " | " + secondMessage);
            }
        }

        // JS parity: fetchWithCallerSessionRecovery (qrLoginService.js:306-320).
        private async Task<T> WithCallerSessionRecoveryAsync<T>(Func<Task<T>> requestFactory, CancellationToken ct)
        {
            await EnsureQrSessionAuthenticatedAsync(false, ct).ConfigureAwait(false);

            try
            {
                return await requestFactory().ConfigureAwait(false);
            }
            catch (NuvioHttpException ex) when (IsCallerSessionRejected(ex))
            {
                await EnsureQrSessionAuthenticatedAsync(true, ct).ConfigureAwait(false);
                return await requestFactory().ConfigureAwait(false);
            }
        }

        private static bool IsCallerSessionRejected(NuvioHttpException ex)
        {
            if (ex.Status == 401)
            {
                return true;
            }

            var message = Flatten(ex).ToLowerInvariant();
            foreach (var marker in CallerRejectedMarkers)
            {
                if (message.Contains(marker))
                {
                    return true;
                }
            }

            return false;
        }

        // JS parity: isLegacyStartSignatureError (qrLoginService.js:128-135).
        private static bool IsLegacyStartSignatureError(string text)
        {
            var message = (text ?? "").ToLowerInvariant();
            return message.Contains("start_tv_login_session")
                && message.Contains("could not find the function")
                && message.Contains("p_device_name");
        }

        private static string Flatten(NuvioHttpException ex)
        {
            return string.Join(" ", ex.Message ?? "", ex.Detail ?? "", ex.Code ?? "");
        }

        // -------------------------------------------------------------------
        // Helpers
        // -------------------------------------------------------------------

        // JS parity: hasQrAuthConfig (qrLoginService.js:10-12).
        private static bool HasQrAuthConfig()
        {
            return !string.IsNullOrEmpty(AppConfig.SupabaseUrl) && !string.IsNullOrEmpty(AppConfig.SupabaseAnonKey);
        }

        // JS parity: generateDeviceNonce (qrLoginService.js:54-73) — crypto.randomUUID
        // canonical form; Guid "D" format matches (lowercase, hyphenated, 36 chars).
        private static string GenerateDeviceNonce()
        {
            return Guid.NewGuid().ToString("D");
        }

        // JS parity: buildRedirectCandidates (qrLoginService.js:96-113). Native has no
        // window.location, so the base comes from TvLoginWebBaseUrl only.
        private static List<string> BuildRedirectCandidates()
        {
            var candidates = new List<string>();
            var baseUrl = AppConfig.TvLoginWebBaseUrl;
            if (!string.IsNullOrWhiteSpace(baseUrl))
            {
                baseUrl = baseUrl.Trim();
                candidates.Add(baseUrl);
                candidates.Add(baseUrl.EndsWith("/", StringComparison.Ordinal)
                    ? baseUrl.TrimEnd('/')
                    : baseUrl + "/");

                var origin = ExtractOrigin(baseUrl);
                if (origin != null)
                {
                    candidates.Add(origin);
                    candidates.Add(origin + "/");
                }
            }

            var unique = new List<string>();
            foreach (var candidate in candidates)
            {
                if (!string.IsNullOrEmpty(candidate) && !unique.Contains(candidate))
                {
                    unique.Add(candidate);
                }
            }

            return unique;
        }
        // JS parity: extractOrigin (qrLoginService.js:88-94). netstandard2.0 has no
        // Uri.Origin, so build scheme://host[:port] manually (default ports omitted).
        private static string ExtractOrigin(string url)
        {
            try
            {
                var uri = new Uri(url);
                if (uri.Scheme != "http" && uri.Scheme != "https")
                {
                    return null;
                }

                var portSuffix = uri.IsDefaultPort ? "" : ":" + uri.Port.ToString(System.Globalization.CultureInfo.InvariantCulture);
                return uri.Scheme + "://" + uri.Host + portSuffix;
            }
            catch
            {
                return null;
            }
        }

        // JS parity: toEpochMillis (qrLoginService.js:115-126).
        private static long ToEpochMillis(JsonElement session, Func<DateTimeOffset> utcNow)
        {
            var millis = GetNumberProperty(session, "expires_at_millis");
            if (millis.HasValue)
            {
                return (long)millis.Value;
            }

            var expiresAt = GetStringProperty(session, "expires_at");
            if (expiresAt != null && DateTimeOffset.TryParse(expiresAt, out var parsed))
            {
                return parsed.ToUnixTimeMilliseconds();
            }

            return utcNow().ToUnixTimeMilliseconds() + SessionExpiryFallbackMillis;
        }

        private string GetDeviceLabel()
        {
            return _deviceLabelProvider != null ? _deviceLabelProvider() : "Tizen TV";
        }

        // JS parity: extractSessionTokens (qrLoginService.js:193-205).
        internal static bool TryExtractSessionTokens(JsonElement payload, out string accessToken, out string refreshToken)
        {
            accessToken = null;
            refreshToken = null;

            if (payload.ValueKind != JsonValueKind.Object)
            {
                return false;
            }

            accessToken = GetStringProperty(payload, "access_token")
                ?? GetStringProperty(payload, "accessToken")
                ?? GetNestedStringProperty(payload, "session", "access_token");

            refreshToken = GetStringProperty(payload, "refresh_token")
                ?? GetStringProperty(payload, "refreshToken")
                ?? GetNestedStringProperty(payload, "session", "refresh_token");

            return !string.IsNullOrEmpty(accessToken) && !string.IsNullOrEmpty(refreshToken);
        }

        private static JsonElement? FirstArrayElement(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Array && element.GetArrayLength() > 0)
            {
                return element[0];
            }

            return null;
        }

        private static double? GetNumberProperty(JsonElement element, string propertyName)
        {
            if (element.ValueKind != JsonValueKind.Object)
            {
                return null;
            }

            if (!element.TryGetProperty(propertyName, out var property) || property.ValueKind != JsonValueKind.Number)
            {
                return null;
            }

            return property.GetDouble();
        }

        private static double ToNumber(double? value, double fallback)
        {
            return value.HasValue ? value.Value : fallback;
        }

        private static string GetStringProperty(JsonElement element, string propertyName)
        {
            if (element.ValueKind != JsonValueKind.Object)
            {
                return null;
            }

            if (!element.TryGetProperty(propertyName, out var property))
            {
                return null;
            }

            if (property.ValueKind == JsonValueKind.String)
            {
                var value = property.GetString();
                return string.IsNullOrWhiteSpace(value) ? null : value;
            }

            return null;
        }

        private static string GetNestedStringProperty(JsonElement element, string containerProperty, string propertyName)
        {
            if (element.ValueKind != JsonValueKind.Object)
            {
                return null;
            }

            if (!element.TryGetProperty(containerProperty, out var container) || container.ValueKind != JsonValueKind.Object)
            {
                return null;
            }

            return GetStringProperty(container, propertyName);
        }
    }
}
