using System;
using System.Threading;

namespace NuvioTV.Tizen.Input
{
    /// <summary>
    /// OK-hold detection (webapp hold-OK 650ms): key down starts the timer,
    /// key up before the threshold cancels it. Long-press fires exactly once.
    /// Also exposes SuppressEnterUntilKeyUp semantics: after a long-press the
    /// subsequent release must not be treated as a click.
    /// </summary>
    public sealed class HoldTimerService : IDisposable
    {
        private readonly Timer _timer;
        private readonly Action _onLongPress;
        private readonly int _holdMs;
        private bool _fired;
        private bool _suppressNextClick;

        public HoldTimerService(Action onLongPress, int holdMs = 650)
        {
            _onLongPress = onLongPress ?? throw new ArgumentNullException(nameof(onLongPress));
            _holdMs = holdMs;
            _timer = new Timer(OnTimer, null, Timeout.Infinite, Timeout.Infinite);
        }

        /// <summary>True when the next click should be swallowed (post long-press).</summary>
        public bool ShouldSuppressClick()
        {
            if (_suppressNextClick)
            {
                _suppressNextClick = false;
                return true;
            }
            return false;
        }

        public void OnKeyDown()
        {
            _fired = false;
            _suppressNextClick = false;
            _timer.Change(_holdMs, Timeout.Infinite);
        }

        public void OnKeyUp()
        {
            _timer.Change(Timeout.Infinite, Timeout.Infinite);
            if (_fired)
            {
                // Long-press already fired: suppress the click generated by release.
                _suppressNextClick = true;
                _fired = false;
            }
        }

        public void Cancel()
        {
            _timer.Change(Timeout.Infinite, Timeout.Infinite);
            _fired = false;
        }

        private void OnTimer(object state)
        {
            if (_fired) return;
            _fired = true;
            _onLongPress();
        }

        public void Dispose()
        {
            _timer?.Dispose();
        }
    }
}
